README.md

Adding logo to readme

---

_config.yml
css/custom.css
index.html

1. Updated subjumbotron background to the datamonkey purple color fixed favicon link, 
2. Updated download link
3. Fixed favicon rel link
4. Updated twitter handle

Minor site changes

---

.travis.yml
res/TemplateBatchFiles/files.lst

* removing v2.3-alpha branch from integration tests
* fixing typo in files.lst

test and typo updates

---

res/TemplateBatchFiles/SelectionAnalyses/RELAX.bf

For consistency with manuscript

Changed incorrect model exploratory name to say descriptive

---

res/TemplateBatchFiles/ProteinAnalyses/ProteinGTRFit.bf
res/TemplateBatchFiles/ProteinAnalyses/ProteinGTRFit_helper.ibf
res/TemplateBatchFiles/ProteinAnalyses/relative_prot_rates.bf
res/TemplateBatchFiles/files.lst

Brought amino acid analyses up to speed, both in terms of debugging and improved functionality. Analyses additionally added to hyphy menu prompt (#3).

ProteinAnalyses update

---

res/TemplateBatchFiles/SelectionAnalyses/BUSTED.bf

Removed deprecated and duplicated old store_lf code

BUSTED fix

---

res/TemplateBatchFiles/SelectionAnalyses/aBSREL.bf

Store analysis banner to JSON.
This change will not have any bearing on vision parsing.

aBSREL updated

---

.travis.yml
res/TemplateBatchFiles/SelectionAnalyses/MEME.bf
tests/hbltests/libv3/BUSTED.wbf
tests/hbltests/libv3/MEME-partitioned.wbf
tests/hbltests/libv3/RELAX.wbf

Simply runs the batch file and ensures it completes

Adding initial tests for RELAX and BUSTED

---

res/TemplateBatchFiles/ProteinAnalyses/ProteinGTRFit.bf
res/TemplateBatchFiles/ProteinAnalyses/ProteinGTRFit_helper.ibf
res/TemplateBatchFiles/ProteinAnalyses/relative_prot_rates.bf
res/TemplateBatchFiles/relative_nucleotide_rates.bf
tests/hbltests/libv3/ProteinGTRFit.wbf

Description print-out had "rate4site" had been replaced with batchfile name...

Protein Relative Rate improvements and patches

---

res/TemplateBatchFiles/LEISR.bf
res/TemplateBatchFiles/libv3/models/protein/empirical.bf
tests/hbltests/libv3/LEISR.wbf

JSON now has similar fields to SelectionAnalyses methods, and prompt is the same for nucleotides and proteins. We now force +F for AA, since this is the right choice anyhow.

Updates to LEISR JSON and prompt 

---

src/core/calcnode.cpp

This fixes a clang compiler error.

Use '!iterator->is_root()' instead of 'iterator->is_root() == nil'

---

README.md

Change cmake -DINSTALL_PREFIX to cmake -DCMAKE_INSTALL_PREFIX

Install to custom location should be: cmake -DCMAKE_INSTALL_PREFIX

---

tests/hbltests/UnitTests/HBLCommands/Caret.bf
tests/hbltests/UnitTests/HBLCommands/DoubleVerticalBar.bf
tests/hbltests/UnitTests/HBLCommands/If.bf
tests/hbltests/UnitTests/HBLCommands/Transpose.bf
tests/hbltests/UnitTests/HBLCommands/ZCDF.bf

Only major question is how to handle AVL trees in the Caret (^) operator test.

Unit tests for DoubleVerticalBar (||), ZCDF, Transpose, Caret (^), If.

---

CMakeLists.txt

This PR merges veg/beta into the develop branch using the `--strategy=ours` git option.

Merge ours

---

res/TemplateBatchFiles/files.lst
src/core/include/hy_strings.h
src/mains/unix.cpp
test_kwargs.sh

__New Help Message:__  
__Old Help Message:__ (continues off screenshot)

Edits to the help message

---

src/mains/unix.cpp

Consolidates the `-h` and `--help` messages. Now they both print the same message. Basically the same as the old `-h` message with minor edits and now including the list of standard analyses (which is what the old `--help` message was):

Help message (merge -h and --help)

---

res/TemplateBatchFiles/GARD.bf
res/TemplateBatchFiles/libv3/convenience/random.bf
src/core/batchlan.cpp

Fix issue 1077 and other GARD-related bugs.

GARD fixes

---

src/core/dataset.cpp

Fix FreeBSD build error

---

README.md

Hi @spond --  as discussed in #1598 here is a PR with a bit of info on the FIFO interface to the CLI. Let me know if there is anything you'd like me to add here. 
This PR closes #1598

adding notes about CLI usage

---

CMakeLists.txt

Code cleanup and refactoring. CMakeLists

GCC 9 minimum
